### ISSUE TITLE
Dokkie in a subfolder

### ISSUE THREAD

**Issue by silvandiepen** [silvandiepen/dokkie#24]
Dokkie doesn't know the domain you deploy to, thus it cant use the url in the link to the assets like styling when deployed in a subfolder. This results in non existing styling. 

Need to get the url in the generation process.

**Comment by dipsaus9** [comment]
Maybe Dokkie can access a NODE ENV so you can change it according to your development mode (production, staging or dev?). This way you can run npx dokkie according to your previously set ENV in Github or Netlify.

**Comment by silvandiepen** [comment]
Not a bad idea, but in that case I think it should be possible to set almost all config in the ENV. Should think of a way to fix this and keep this logical.

**Comment by silvandiepen** [comment]
fixed. ENV still in process #38
